### ISSUE TITLE
Account Internal Server Error

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-civic-europe#100]
URL: https://ce-dev.liqd.net/accounts/edit/

behavior: Internal Server Error

**Comment by mcastro-lqd** [comment]
![Screenshot 2020-03-11 at 14 42 02](https://user-images.githubusercontent.com/59610786/76423054-7fea3d80-63a6-11ea-89c1-5ce154e61375.png)

**Comment by fuzzylogic2000** [comment]
@rmader This is the same as on Monday, but this time only in the account settings, not in the wizard step "Idea". Last time it broke because of the imageupload (which are in both). This time: no idea! But maybe some js-stuff again? Or didn't we include the endpoint to use there or somethng?

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 actually I wrote it not moritz, so I don't know about Mondays problem haha

but I just wanted to leave registred :)
