### ISSUE TITLE
#2709 No Notification is send for Shortlist and Winners - will be tested again!!

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#105]
**URL:** https://ce-dev.liqd.net/ideas/
**user:** admin
**expected behaviour:** If I set the shortlist and winners in Django and click on send notification to shortlisted/Winners these Participants should get an e-mail
**behaviour:** If I set the shortlist and winners in Django and click on send notification to shortlisted/Winners these Participants don't get teh notification mail 
**important screensize:**desktop
**device & browser:**  Desktop, firefox 73.0.1 (64-Bit)*

**Comment by fuzzylogic2000** [comment]
Yeah, it is only send to the followers of the idea. The creators are contacted seperately by "normal" email.

**Comment by phillimorland** [comment]
this is working on dev so will close
