### ISSUE TITLE
#2709 Notification after submitting an idea

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#107]
**URL:** https://ce-dev.liqd.net/ideas/
**user:** participants
**expected behaviour:**in the notification mail the participant received  "(...)up to fifteen winning ideas(...) should be bold

**Comment by phillimorland** [comment]
@hello-kathi just to confirm, this is an issue to do with an email? for future, if this is the case, you don't need to add a url. Or have I not understood the issue?

**Comment by Rineee** [comment]
covered by #114, right?
