### ISSUE TITLE
Civic Europe - General Comments 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-civic-europe#111]
**URL:** https://ce-dev.liqd.net/

**Comment/Question:** 

Hi, here is some stuff I noticed while using the platform. Probably you are already working on some of them, but I just wanted to have them registered here to be safe. 

01 – Only one tile size is different. 
![Screenshot 2020-03-12 at 15 43 37](https://user-images.githubusercontent.com/59610786/76537686-70d6be80-647e-11ea-889e-ee6f0c960557.png)

02 – Are we really using this picture as the main banner? Would it be better here to include a CTA like "Add Idea Now"
![Screenshot 2020-03-12 at 14 56 55](https://user-images.githubusercontent.com/59610786/76537894-b85d4a80-647e-11ea-8e35-fbcdf8a160a1.png)

03 – Missing info here
![Screenshot 2020-03-12 at 14 42 44](https://user-images.githubusercontent.com/59610786/76538091-096d3e80-647f-11ea-99d3-46bdd5e59a62.png)

04 – Shall we put a character limit here or make it all lower case? What do you think? 
![Screenshot 2020-03-11 at 15 01 29](https://user-images.githubusercontent.com/59610786/76538160-273aa380-647f-11ea-8b62-b2d70e43e15d.png)

**Mobile:** 
05 – It seems to me that something is missing here, showing the user that it's possible to swipe left. Do you guys agree? (I just made a quick sketch on Photoshop to explain better)
![Screenshot 2020-03-12 at 16 00 08](https://user-images.githubusercontent.com/59610786/76540988-328fce00-6483-11ea-8837-61ff89f18e3f.png)

06 – When I was creating a New Idea, the continue button was always cropped, is there a way to fix it?
![IMG_6105](https://user-images.githubusercontent.com/59610786/76541357-bd70c880-6483-11ea-9010-9f1738d0e40d.PNG)

07 – Also here half of the User button + Arrow are cropped, it gets difficult to click and access. 
![IMG_6104](https://user-images.githubusercontent.com/59610786/76541919-936bd600-6484-11ea-8fb7-e8e41d65de22.PNG)
![IMG_6103](https://user-images.githubusercontent.com/59610786/76541610-28220400-6484-11ea-8b0f-02f6e03ad3b3.PNG)

08 – Regarding the Newsletter, I think we should def avoid center align paragraph texts cause it really difficult the readability. The difficulty with centered text is that it can be hard for the eye to know where things start and stop since lines are ragged on both sides of the copy block.
![Screenshot 2020-03-12 at 14 48 41](https://user-images.githubusercontent.com/59610786/76542462-4b00e800-6485-11ea-9612-833b2e6ef11d.png)

Daaanke!

**Comment by hello-kathi** [comment]
01) I have the same
<img width="1155" alt="Bildschirmfoto 2020-03-13 um 16 01 11" src="https://user-images.githubusercontent.com/52459078/76632741-f8d2cc00-6543-11ea-9713-bf773218d3ed.png">
02) It is a placeholder
03) They have to fill in the Terms of conditions
08) I agree!

**Comment by phillimorland** [comment]
02) we can have a cta there and a video button if we like, same as advocate europe
06) @mcastro-lqd can I have size and device that happens on?
08) we use a single email base so if we left align text for this email, it will be left aligned for all emails, including the single line ones, do we want that? @hello-kathi @mcastro-lqd

**Comment by phillimorland** [comment]
05) this is what it looks like if I just display the arrows for all screen sizes, what do we think @mcastro-lqd? if we want a new button for smaller screens, it might be a story, also arrows only show up on hover so for touch devices we will need to figure it out, just wondering should I put time into this? @hello-kathi  
![Homepage   Civic Europe(1)](https://user-images.githubusercontent.com/5871230/76771905-56635480-67a0-11ea-8266-e12ccd1c0555.png)

**Comment by mcastro-lqd** [comment]
@phillimorland 
3 – "can I have size and device that happens on?"  I think Kathi already explained that its a place holder right? 

4 – Ah ok, I mean, text blocks should be always aligned to left, I just mentioned cause that's how it should be when it comes to readability. Up to you 2 then :)

5 – I just mentioned that cause it was asked to review the page. If we don't have time, fine but I 
was just a bit unsure if the users would scroll directly down without checking more ideas. 

Thanks!

**Comment by phillimorland** [comment]
5 - all feedback is always welcome! 
6 and 7 cannot reproduce, even on browserstack so not sure how to solve, will create a new issue concerning these and maybe we can revisit it

**Comment by hello-kathi** [comment]
@phillimorland 
2) they will add a picture or video or whatever by themself.
4) i think the readability is a thing. Are the buttons left too or will tehy stay in the middle?
5) mmmh ok I will checkthis again.

**Comment by phillimorland** [comment]
@hello-kathi 
4 - we can keep the buttons in the middle as they are a different block but all writing is in same block
