### ISSUE TITLE
#2586 Text is missing + one Headline in Idea form

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#112]
**URL:** https://ce-dev.liqd.net
**user:** participants
**expected behaviour:** 
1. Idea/About you
Please add:
"Your first and last name will be published together with the application."
<img width="957" alt="Bildschirmfoto 2020-03-13 um 14 21 00" src="https://user-images.githubusercontent.com/52459078/76624694-113bea00-6536-11ea-83e8-af99f3e3d1ec.png">

2. Partner
1.**Please share the names of your partner organisations here.** (line break)
If you do not have any partner organisations, leave the fields empty. You can update these fields any time before the application deadline.

**Comment by Rineee** [comment]
@hello-kathi Should this really be in red or was it just to show us whats missing?

**Comment by fuzzylogic2000** [comment]
@hello-kathi The first one is behaving quite differently from how we usually do it: We do sometimes (only in the partners sections) have a section explanation there, but this should be about the whole wizard page, I would say. Here it's more of a helptext for the names. Can we then add it as a helptext for the names? Either as helptext for "first name" or as helptext to both the first and the last name? 
@Rineee

**Comment by hello-kathi** [comment]
@fuzzylogic2000 @Rineee helptext is fine, great idea! Thank you!
Just first name, I think that is enough...
