### ISSUE TITLE
#2709 Notification Comment added (user watches idea)

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#115]
**URL:** https://ce-dev.liqd.net/ideas/
**user:** *moderator/ initiator/ participants/ visitors (non-logged-in)/ admin/ cms-editors/ developers*
**expected behaviour:** *Subject:
A comment was added to the idea "Example idea title"

Text:
A comment was added to the idea "Example idea title" by Example user name.
 
Call to action-Button:
Visit the comment 

Grauer Infotext im Abbinder:
This email was sent to Example user email adress. This email was sent to you because you are watching an idea. If you no longer wish to receive these notifications, you can unwatch the idea or disable notifications completely in your account settings.*
**behaviour:** 
*Subject
A comment was created by Knopf_user_2
Text:
A comment was added to your idea *

**Comment by phillimorland** [comment]
@hello-kathi just to clarify which text is incorrect, the subject?

**Comment by hello-kathi** [comment]
@phillimorland Subject and Text.
Now we say
*Subject
A comment was created by Knopf_user_2
it should be:
*Subject:
A comment was added to the idea "Example idea title"

In the mail we say now:
Text:
A comment was added to your idea *

it should be:
A comment was added to the idea "Example idea title" by Example user name.

Call to action-Button:
Visit the comment

The grey info text is there already and it is fine!

**Comment by phillimorland** [comment]
ahh it sounds like we're sending the creator notification as a follow notification :( can you forward me the offending email?

**Comment by fuzzylogic2000** [comment]
That email didn't exist in the list of changes, so it got the wrong footer.

**Comment by hello-kathi** [comment]
Do we have to talk about this, or did you do your magic, and all is fine?

**Comment by phillimorland** [comment]
@hello-kathi should be fine!
