### ISSUE TITLE
#2709 if comments are reported, moderator don't get mail

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#116]
**URL:** https://ce-dev.liqd.net/ideas/
**user:** *moderatord*
**expected behaviour:** *If a comment will be reported the modereator should be informed via notification*
**behaviour:** *the moderator gets no notification vi ae-mail*

**Comment/Question:** *Username: Knopf_user_2 is moderator*

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.

**Comment by fuzzylogic2000** [comment]
I couldn't reproduce this, I think it works. Please reopen if not
