### ISSUE TITLE
width of carousel tile too small when very short title and description

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-civic-europe#126]
**URL:** https://ce-dev.liqd.net/
**user:** 
**expected behaviour:** all title should have the same width
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** This shouldn't occur on the real platform, but I think to be safe, we should fix it anyway

![Screenshot from 2020-03-16 17-06-25](https://user-images.githubusercontent.com/8178179/76779522-c62b0c80-67ab-11ea-8b73-55fed0c30f29.png)

**Comment by phillimorland** [comment]
duplicated in design issues and solved
