### ISSUE TITLE
Application form (Wizard) wrong date format

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#140]
**URL:**https://ce-stage.liqd.net/ideas/create/module/idea-challenge-2020/
**user:** *participants*
**expected behaviour:** *I expected the Date Format March 19, 2020 (10:40 CET)*
**behaviour:** *the date format is 19 March 2020*
**important screensize:** desktop*
**device & browser:** *Desktop, firefox 74 (64-Bit)*
**Comment/Question:** *Is it possible to change text, if change the date format to:
Deadline for the submission of project ideas is March 19, 2020 (10:40 CET). If you submit your idea before the deadline, you will still be able to edit your application until this date. Please notice that only applications in English language will be considered. 
*

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.

**Comment by fuzzylogic2000** [comment]
@hello-kathi Where exactly is this? I filled in all steps in the wizard (on stage, where the link goes), but couldn't spot the text. Which step of the wizard and which question is it? Is it only in the create or also in the edit?

**Comment by hello-kathi** [comment]
@fuzzylogic2000 
<img width="1214" alt="Bildschirmfoto 2020-03-30 um 09 26 34" src="https://user-images.githubusercontent.com/52459078/77886164-a5ad8880-7268-11ea-9877-dd4fe6da018d.png">

**Comment by Rineee** [comment]
I cant reproduce the section description, thats so strange...

**Comment by fuzzylogic2000** [comment]
@Rineee You have to be in the right phase to get it. If you add the idea as an admin in another phase, it's not there. The text is here https://github.com/liqd/a4-civic-europe/blob/358e5db8274b703959be7da496974c4e8ffbaf67/apps/ideas/forms.py#L136 and the date is added to the kwargs here https://github.com/liqd/a4-civic-europe/blob/2b3842b76e89d8bcf3c3820bef9f3ab236926352/apps/ideas/views.py#L110
But @phillimorland is already on it now.

**Comment by Rineee** [comment]
Aaaah, always these phases that confuse me :) Thank you for the explanation!
