### ISSUE TITLE
Wizard: Topics Spaces between Check Box and Text

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#141]
**URL:** https://ce-stage.liqd.net/ideas/create/module/idea-challenge-2020/
**user:** *participants*
**expected behaviour:** *I expected a Space between IntroText and Topics. I Expected a Space between checkboxes and Topic *
**behaviour:** *The Intro Text has noch Space between Text and Topics, and no Space between Checkbox and Text*
**important screensize:** *desktop*
**device & browser:** * Desktop, firefox 74
<img width="661" alt="Bildschirmfoto 2020-03-19 um 16 29 04" src="https://user-images.githubusercontent.com/52459078/77084324-1b129100-69ff-11ea-8157-5035622e9067.png">
 (64-Bit)*
**Comment/Question:** *Is this easy to do? What ideas do you have? Would this be a story?*

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.

**Comment by fuzzylogic2000** [comment]
@phillimorland Didn't manage to do it today. So will unassign. Maybe something for you then?
