### ISSUE TITLE
Font Color: Sorry, no ideas exist for the chosen filters. should be white

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#143]
**URL:** https://ce-stage.liqd.net/ideas/?ordering=newest&status=&project=2&country=PT
**user:** *participants*
**expected behaviour:** *I'd expected the text " Sorry, no ideas exist for the chosen filters. should be white" in the Idea Space  in white*
**behaviour:** *The font is black*
**important screensize:** *desktop*
**device & browser:** *Desktop, firefox 74
<img width="1237" alt="Bildschirmfoto 2020-03-19 um 16 35 43" src="https://user-images.githubusercontent.com/52459078/77085005-01257e00-6a00-11ea-8cec-8c96c9153dc2.png">
 (64-Bit)*
**Comment/Question:** *Is this easy to do? What ideas do you have? Would this be a story?*

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.

**Comment by fuzzylogic2000** [comment]
@phillimorland Didn't manage to do it today. So will unassign. Maybe something for you then?
