### ISSUE TITLE
Notification: Submitting your idea

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#144]
**URL:** 
**user:** *participants*
**expected behaviour:** *In the mail text it said civic-europe.eu, 
Date Format is March 19, 2020, 
We are looking forward to an exciting exchange of thoughts and ideas on civic-europe.eu!

Your civic-europe Team 

All co-workers can edit the text until the application deadline and will appear as team members in your project ideas.
*
**behaviour:** *Find out more about the selection process and each phase of the idea challenge on www.civic-europe.de. 

You can edit your idea until 19 March 2020 (17:00 CET). 

We are looking forward to an exciting exchange of thoughts and ideas on example.com!

Your example.com Team 
All co-workers can edit the text until the application deadline and will appear as team members in your project idea*

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.

**Comment by fuzzylogic2000** [comment]
So, the time should also not be there? Or should we change it to "March 19, 2020 (17:00 CET)"?

**Comment by hello-kathi** [comment]
The Time should be change into March 19, 2020 (17:00 CET)
