### ISSUE TITLE
Social Log In is missing

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#145]
**URL:** https://ce-stage.liqd.net/accounts/signup/?next=/
**user:** *participants*
**expected behaviour:** *As  a participant I want to register with Facebook and Google (Twitter optional)*
**behaviour:** *There is no Social Log in/ Registration possibility right now*
**important screensize:** *desktop*
**device & browser:** *Desktop, firefox 74 (64-Bit)*
**Comment/Question:** *Is this easy to do? What ideas do you have? Would this be a story?*

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.

**Comment by fuzzylogic2000** [comment]
@rmader Did you already do this? We only have until next week.

**Comment by hello-kathi** [comment]
@fuzzylogic2000 @rmader We have it on dev. I tested it, it is fine and can be deployed if its ready

**Comment by rmader** [comment]
I think the facebook one is not completely set up. Need to do that with moritz.

**Comment by fuzzylogic2000** [comment]
This is fixed, right? Reopen @hello-kathi or @rmader if isn't!
