### ISSUE TITLE
Using the "Notify Shortlist Idea Challange 2020" Send out community Award message

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#146]
**URL:** https://ce-stage.liqd.net/
**user:** * participants/admin*
**expected behaviour:** *If I send out Notification Shortlist via Django, I want to send the shortlist notification*
**behaviour:** *If I send out the shortlist notification, the follower will get Winning Community Award mail*
**important screensize:** *desktop*
**device & browser:** *Desktop, firefox 74
<img width="587" alt="Bildschirmfoto 2020-03-19 um 17 30 51" src="https://user-images.githubusercontent.com/52459078/77090412-67fa6580-6a07-11ea-8645-d304029fe29d.png">
 (64-Bit)*
**Comment/Question:** *Is this easy to do? What ideas do you have? Would this be a story?*

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.

**Comment by fuzzylogic2000** [comment]
Oh my, when the idea is on the shortlist and has won the community award, the community award email is sent out. If ideas are only on the shortlist and haven't won the community award, the shortlist-notification is sent out. If ideas have only won the community award, nothing is sent out.

**Comment by fuzzylogic2000** [comment]
Oh, in earlier years, the community award was a way to get on the shortlist, I think. And it's still like that, right? So this might be why the code is so weird and a feature not a bug!
@hello-kathi Should it stay like this, then? We should change the text of the email, then, though and document this!

**Comment by fuzzylogic2000** [comment]
@hello-kathi What should the text-change of the community award email be? Or should it stay like it's now? It will be sent out, when some idea is on the shortlist because it won the community award. So, maybe the same text as the shortlist email, but also mentioning the community award?

**Comment by hello-kathi** [comment]
I am waiting for the Text Change from MitOst.

**Comment by hello-kathi** [comment]
@fuzzylogic2000 so the new message is there:
"The idea "la" is the community award winner of the civic-europe.eu Idea challenge 2020 competition. Community award winners are automatically shortlist candidates for the idea challenge."

Thank you!
