### ISSUE TITLE
Notification: Invitation Mail // Typo

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#147]
**URL:** https://ce-stage.liqd.net
**user:** *participants*
**expected behaviour:** *In the invation Mail it should be "... you will appeare with your user name..." *
**behaviour:** *you will appeare with you user name...."*
**important screensize:** *desktop*
**device & browser:** * Desktop, 74 (64-Bit)*
**Comment/Question:** *Is this easy to do? What ideas do you have? Would this be a story?*

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.
<img width="410" alt="Bildschirmfoto 2020-03-19 um 17 43 33" src="https://user-images.githubusercontent.com/52459078/77091681-2c609b00-6a09-11ea-9e42-363ed75e0b93.png">

**Comment by fuzzylogic2000** [comment]
Sorry, I can't spot the difference?

**Comment by hello-kathi** [comment]
There is a typo it says "you user name" instead of "your user name". So the r is missing.

**Comment by fuzzylogic2000** [comment]
Ahhh! :smile_cat:
