### ISSUE TITLE
Winners Phase - Phase Description in Idea Space

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#148]
**URL:** https://ce-stage.liqd.net/ideas/
**user:** *participants*
**expected behaviour:** *There is no Phase description shown in idea space during winners phase*
**behaviour:** *In winners Phase he Phase Description from Django is shown in the ideaspace*
**important screensize:** *mobile? desktop?*
**device & browser:** *e.g. Desktop, firefox 68.0.2 (64-Bit)*
**Comment/Question:** *Is this easy to do? What ideas do you have? Would this be a story?*

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.
<img width="1211" alt="Bildschirmfoto 2020-03-19 um 17 45 45" src="https://user-images.githubusercontent.com/52459078/77092077-b6a8ff00-6a09-11ea-8494-8103f4ae72ff.png">

**Comment by fuzzylogic2000** [comment]
But you can see the description even on the screenshot?
