### ISSUE TITLE
It is possible do add&edit ideas during winners phase

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#149]
**URL:** https://ce-stage.liqd.net/ideas/
**user:** *participants*
**expected behaviour:** *During Winners phase all idea space is closed, ideas can't be  edited, but winner ideas can enter jounrey*
**behaviour:** *Winners are able to set Journey Entry, but all participants can add ideas or edit ideas*
**important screensize:** *mobile? desktop?*
**device & browser:** *e.g. Desktop, firefox 68.0.2 (64-Bit)*
**Comment/Question:** *Is this easy to do? What ideas do you have? Would this be a story?*

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.

**Comment by fuzzylogic2000** [comment]
Oh my! Good that you found that! There will be more phases where that happens.
Due to: https://github.com/liqd/a4-civic-europe/blob/3a13784113377fabb66179947e35ff4d9709523c/apps/ideas/phases.py#L39
