### ISSUE TITLE
Notification came from example.com

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#151]
**URL:** https://ce-stage.liqd.net/ideas/
**user:** *participants*
**expected behaviour:** *Notifications should come from Civic Europe. in all the notification texts is civic europe.*
**behaviour:** *In the text ider the sender example.com and not civic europe*
**important screensize:** *desktop*
**device & browser:** *Desktop, firefox 74 (64-Bit)*
**Comment/Question:** *Is this easy to do? What ideas do you have? Would this be a story?*

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.

<img width="579" alt="Bildschirmfoto 2020-03-20 um 08 37 12" src="https://user-images.githubusercontent.com/52459078/77144446-383e7280-6a86-11ea-8e42-321a658c628c.png">
<img width="519" alt="Bildschirmfoto 2020-03-20 um 08 36 57" src="https://user-images.githubusercontent.com/52459078/77144449-3a083600-6a86-11ea-89ac-215525d41f68.png">

**Comment by fuzzylogic2000** [comment]
fixed!
