### ISSUE TITLE
Jump Marker on Wagtail jumps to far the section header is hidden

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#156]
**URL:** https://hidden.civic-europe.eu/terms-use/
**user:** *admin/ cms-editors/ developers*
**expected behaviour:** *IWhen I create a structured page, I can jump to your individual chapters using the jump labels*
**behaviour:** *It jumps not on the header, more somewhat deeper*
**important screensize:** *desktop*
**device & browser:** *Desktop, firefox 73 (64-Bit)*ta.

**Comment by hello-kathi** [comment]
@phillimorland you are right, during testing, the toddler hat the mouse...

**Comment by phillimorland** [comment]
@hello-kathi haha ok, so is the issue now that the section header is hidden?

**Comment by fuzzylogic2000** [comment]
@phillimorland @hello-kathi What is the status here? We only have two days left until 1st of April and we wanted to finish it before!

**Comment by hello-kathi** [comment]
Ah sorry @fuzzylogic2000 and @phillimorland I just changed the issue and didn't mentioned it.

**Comment by phillimorland** [comment]
ok will fix today
