### ISSUE TITLE
CE Stories new article date is shown uncorrect

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#225]
**URL:** https://ce-stage.liqd.net/admin/pages/10/
**user:** *moderator admin/ cms-editors/ developers*
**expected behaviour:** *Wagtail, Stories, adding Childpage instert Authore Name and the date, the date is shown correct*
**behaviour:** *Wagtail, Stories, adding Childpage instert Authore Name and the date, the date is shown uncirrect and adds new random date (Screenshot)*
**important screensize:** *desktop*
**device & browser:** * Desktop, firefox 77.0.1 (64-Bit*
**Comment/Question:** 

<img width="904" alt="Bildschirmfoto 2020-06-15 um 08 30 12" src="https://user-images.githubusercontent.com/52459078/84624993-af976d00-aee2-11ea-8149-db952950618e.png">

**Comment by phillimorland** [comment]
@hello-kathi the template adds the date of the last time the page was published automatically so typing an additional date into the author name section will cause it to list 2 dates so you need to remove the added date, if you want to be able to choose a publication date then I think that's a story, hope that helps! :)

**Comment by hello-kathi** [comment]
@phillimorland ah makes sense! Thank you!
