### ISSUE TITLE
#3555 - [Civic Europe] Add an 1 to 3 columns block to wagtail

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-civic-europe#318]
**URL:** https://ce-dev.liqd.net/
**important screensize:** *Both*
**device & browser:** *Safari and Chrome*
**Comment/Question:** *Added some small comments here*

[201221-m-add-an-1-to-3-columns-block-to-wagtail .pdf](https://github.com/liqd/a4-civic-europe/files/5739148/201221-m-add-an-1-to-3-columns-block-to-wagtail.pdf)

[201221-d-add-an-1-to-3-columns-block-to-wagtail .pdf](https://github.com/liqd/a4-civic-europe/files/5739147/201221-d-add-an-1-to-3-columns-block-to-wagtail.pdf)

**Comment by phillimorland** [comment]
@mcastro-lqd wagtail richtext editor does not have a text align option, if that what you're asking? I'm not totally sure?!

**Comment by mcastro-lqd** [comment]
@phillimorland Regarding which comment?

**Comment by phillimorland** [comment]
@mcastro-lqd it's not numbered: 
"liquid-designer12/24/2020, 10:51:39 AM
Is it possible to center this text vertically on Wegtail? "

**Comment by mcastro-lqd** [comment]
@phillimorland It's the only one for desktop. It was just because the CTAs seems more closer to the bottom than the top part. but if it can't be changed all good, I just mentioned because I have to mention what is wrong
