### ISSUE TITLE
Multiple choice in country field not really intuitive

### ISSUE THREAD

**Issue by rmader** [liqd/a4-civic-europe#320]
**URL:** https://ce-dev.liqd.net/ideas/add-people-who-are-not-liqdnet-mails/edit/2/
**user:** 
**expected behaviour:** As a average user I immediately know how to select multiple countries
**behaviour:** I need to know that I need to hold *shift* while clicking multiple countries to not lose the former selection
**important screensize:**
**device & browser:** desktop firefox. Probably similar on most platforms
**Comment/Question:** 

Screenshot?
![image](https://user-images.githubusercontent.com/6313774/103082269-fbd21100-45d9-11eb-9440-6afd1b4d604d.png)

**Comment by fuzzylogic2000** [comment]
@Rineee This is not multiple anymore, right?

**Comment by Rineee** [comment]
@fuzzylogic2000 Yes, it still is multiple.. and I agree that it is not very intuitive. It is a country field with 'multiple=True'. We could either use checkboxes instead (but then it would be inconsistent with the other country dropdowns) or maybe just a note in the helptext to press shift to select multiple?

**Comment by Rineee** [comment]
But maybe lets just wait what MitOst says after testing?

**Comment by hello-kathi** [comment]
Hello, @Rineee @fuzzylogic2000 MitOst would like to have a multiple Choice with Checkboxes here. I hope that is possible and okish?
