### ISSUE TITLE
Missing topics in "field of action" 

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-civic-europe#328]
Topics are missing in the filter and in the applictaion form.

**URL:** https://ce-dev.liqd.net/ideas/create/module/idea-challenge-2020/
AND 
**URL:** https://ce-dev.liqd.net/ideas/
**user:** non-logged in user
**expected behaviour:** all topics are indicated
**behaviour:** missing topic in filter: 
- Education and research
- Health
- Law, advocacy and policy

**Comment/Question:** Or was it not possible to implement these ones?

**Comment by Rineee** [comment]
duplicate of  #317
