### ISSUE TITLE
long topic in "field of action" goes out of box

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-civic-europe#329]
**URL:** https://ce-dev.liqd.net/ideas/?ordering=newest&status=field_of_action=YP
**user:** non logged in user
**expected behaviour:** wording adapts
**behaviour:** "Youth participation and empowerment" crosses field
**important screensize:** desktop 
**device & browser:** Chrome latest version on windows 10, desktop

<img width="464" alt="Bildschirmfoto 2021-01-04 um 12 50 21" src="https://user-images.githubusercontent.com/30862422/103532750-13d44b00-4e8c-11eb-8ece-e3def3ad9f85.png">

**Comment by fredewe** [comment]
Same in latest Chrome version on MacOS 11.0.1. On Safari it works well.

**Comment by Rineee** [comment]
@fuzzylogic2000 @rmader I couldnt fix this. Tried to insert a fixed height of 200px to [this class](https://github.com/liqd/a4-civic-europe/blob/757a9677f94bab6b1135c5e48fe86b2c3e2dade2/civic_europe/assets/scss/components/_filters.scss#L61), which kind of worked, but then it clashes (I think) with the media query below for window size btw 1200 and 1000..

**Comment by fuzzylogic2000** [comment]
Yeah, the media query doesn't make a lot of sense and makes it always look pretty broken on mobile. :woman_shrugging:

**Comment by fuzzylogic2000** [comment]
I think they used to be half the size on mobile. There's also a weird right-class. (Most likely all added by me 4 years ago :grimacing: )
