### ISSUE TITLE
Uploading Image in Wizzard is weird

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#33]
**URL:** 
https://ce-dev.liqd.net/ideas/create/module/idea-challenge-2020/
**user:** 
Katharina M
**expected behaviour:** 
When I upload an image in the wizard I expect a small preview image.
**behaviour:** 
When I upload an image in the wizard, the image is displayed in its original size and mostly cropped. I have to scroll along the whole image to get to the next field.
**important screensize:**
Laptop

**device & browser:** 
MacBook Firefox72.0.2 (64-Bit)
**Comment/Question:** 
<3

Screenshot?
<img width="1279" alt="Bildschirmfoto 2020-01-27 um 10 00 25" src="https://user-images.githubusercontent.com/52459078/73161554-1232cc80-40ec-11ea-895f-8faa9bab3256.png">
<img width="1242" alt="Bildschirmfoto 2020-01-27 um 10 00 37" src="https://user-images.githubusercontent.com/52459078/73161556-1232cc80-40ec-11ea-8994-132b88cdbae9.png">

**Comment by fuzzylogic2000** [comment]
fixed by #57 and #68
