### ISSUE TITLE
Wording in application form

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-civic-europe#333]
There are some wording issues:

1) About You
- Description Clarification legal Status: Add Full stop after brackets ("If you selected “Other,” please provide details about your current organization status (max. 200 characters)."
- Description Lead Organisation details: Add full stop after brackets and delete in front of bracket ("Please describe main goals, vision and activities of your organization (max. 500 characters)."
- Description Lead Organisation online presence(...): Add "This section will be published in the idea space." after description ("Please enter the website of your organization here. If you don’t have one, please enter your Facebook page or similar online presence. This section will be published in the idea space.")
- Description Location: Delete "Partner": ("...the ideas. If your organization...")
- Multiple Choice selection of Location: Change km2 = sq km ("City/urban area (population of at least 50,000 inhabitants and a density of >1,500 inhabitants per sq km, most inhabitants have nonagricultural jobs, there is good infrastructure such as housing, commercial buildings, roads, bridges, and railways) ... Town (population of at least 5,000 inhabitants and a density of at least 300 inhabitants per sq km)")

2) Partners
- Description "Please share information about your partner organisations here": Add "The names of your partner organizations and their online presence will be published in the idea space." in the end ("If you don't have any partner organisations, leave the fields empty. You can update these fields any time before the application deadline. The names of your partner organisations and their online presence will be published in the idea space.")

Screenshots are in the comments. Sorted by application form category.

**Comment by fredewe** [comment]
Screenshots for 1. About You:

![Bildschirmfoto 2021-01-04 um 17 13 45](https://user-images.githubusercontent.com/5470479/103556309-e1d5df80-4eb1-11eb-9c1e-15b959464e3a.png)

![Bildschirmfoto 2021-01-04 um 17 24 07](https://user-images.githubusercontent.com/5470479/103556321-e7cbc080-4eb1-11eb-82b0-b677ff6b1ec6.png)

**Comment by Rineee** [comment]
@hmkay Concerning the first 2 issues: since we should do it the same everywhere for consistency, just checking again: throughout the form they gave us, they put the full stop before the brackets most of the time. So should I change it everywhere anyways and put it behind the brackets? Or everywhere before the brackets?

**Comment by fredewe** [comment]
Screenshots for 2. Partners:
![Bildschirmfoto 2021-01-05 um 11 15 29](https://user-images.githubusercontent.com/5470479/103634561-89512180-4f47-11eb-96fd-9d51ee35d779.png)
