### ISSUE TITLE
Application Form: Fun answer to "Year of registration"

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-civic-europe#334]
**URL:** https://ce-dev.liqd.net/ideas/create/module/idea-challenge-2020/
**user:** logged in user
**expected behaviour:** I can only type in a valid year
**behaviour:** If I do not type in a valid year another invalid year is suggested :D (Or is this eurocentric thinking and there actually exists a year 2147483647 and we are super inclusive?!?)

<img width="673" alt="Bildschirmfoto 2021-01-04 um 18 09 19" src="https://user-images.githubusercontent.com/30862422/103560568-41cf8480-4eb8-11eb-835b-320f257fa037.png">

**Comment by Rineee** [comment]
This was actually there before, but will try to fix it anyway. What limit should I set, 2021?

**Comment by fuzzylogic2000** [comment]
Haha, we don't actually use a year here...
@Rineee No, let's put 2050 or 2030 there, so that we don't need to change it every year. Or you get the current year and set that. But that's a bit of an overkill, I would say.

**Comment by hmkay** [comment]
Yes, 2050 sounds good. Or even 9999. In hope that human kind will continue existing....
