### ISSUE TITLE
Number of characters Limit

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#34]
**URL:** 
https://ce-dev.liqd.net/ideas/create/module/idea-challenge-2020/
**user:** 
Katharina M
**expected behaviour:** 
If I enter too many characters in the field, the wizard warns me and tells me how many characters are too many. Then I can work on the text if it fits
**behaviour:** 
The text is partly cut off and the last characters are then indicated as too much. So it's a mixture of Too Many Characters and Warning Message and Just Trim Text. But this only happens with a max. 800 characters field. With max. 100 characters the text is simply cut off and no error message appears.
**important screensize:**
**device & browser:** 
Laptop firefox 72.0.2 (64-Bit)
**Comment/Question:** 
Jesus fed 5,000 people with two fishes and a loaf of bread. That’s not a miracle. That’s tapas.
Screenshot?
<img width="1231" alt="Bildschirmfoto 2020-01-27 um 10 08 31" src="https://user-images.githubusercontent.com/52459078/73162531-44ddc480-40ee-11ea-8f3b-0cd300c85f16.png">
<img width="1252" alt="Bildschirmfoto 2020-01-27 um 10 13 48" src="https://user-images.githubusercontent.com/52459078/73162532-44ddc480-40ee-11ea-971c-cf12432b752e.png">

**Comment by phillimorland** [comment]
@hello-kathi do you know if there was a char count in ae? adding this as a feature might be a story

**Comment by fuzzylogic2000** [comment]
This only happens, when the text is pasted into the field. 
If you type, you can't add more characters once the limit is reached. But if you paste stuff, that is too long, it cuts off the words, not the characters.
The pasting without looking out for character length seems like it would happen a lot during testing, but not a lot during real use.

**Comment by hello-kathi** [comment]
@fuzzylogic2000 @phillimorland For me it is fine, we can close that. But I Think it is a thing, that users are doing copy and paste and don't write all stuff in the fields.

But it is not neccessary for now.
