### ISSUE TITLE
Random sorting in ideaspace is not random - we should make that clear in the name

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-civic-europe#345]
**URL:** https://ce-dev.liqd.net/ideas/ (as soon as it's merged)
**user:** 
**expected behaviour:** If I chose random sorting, I expect the sorting to change on reload.
**behaviour:** As this does not work with the pagination and reading through all ideas, we chose the random filter to change the randomness only once a day.
**important screensize:**
**device & browser:** 
**Comment/Question:** I think that can and should be fixed with thinking about the wording?! Maybe we can say "daily random" in the sorting filter? @mcastro-lqd @hmkay @fredewe @hello-kathi any ideas?

**Comment by rmader** [comment]
Maybe "Random daily selection" is better here? Problem is still that the order also changes when new ideas are posted.

**Comment by mcastro-lqd** [comment]
Yeah, I also thought about that when I saw it, but its really tricky to find an accurate word. Maybe: Just "No Sorting", something like "Our selection" or  "Randomly picked" ?

**Comment by fredewe** [comment]
Daily random would be fine for me.

**Comment by fredewe** [comment]
I think we should stick to "random" or "daily random". But we could also ask the people at MitOst if they have a good idea.
Or is this about the naming in our code?

**Comment by fuzzylogic2000** [comment]
@fredewe Currently it's only about how to show it in the dropdown in CE.

**Comment by fredewe** [comment]
@fuzzylogic2000 @hello-kathi @hmkay Should we ask MitOst then?

**Comment by hello-kathi** [comment]
@fuzzylogic2000 @fredewe @hmkay I have an appointment with MitOst tomorrow and will discuss this with them.

**Comment by hello-kathi** [comment]
@fuzzylogic2000 MitOst is discussing the wording and tells us as soon as possible.

**Comment by hello-kathi** [comment]
@fuzzylogic2000 @Rineee @phillimorland @rmader So we have the naming: "daily random" 
🥳
