### ISSUE TITLE
Internal Error - Sorting Idea Space

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#35]
**URL:** 
https://ce-dev.liqd.net/ideas/?ordering=support&status=&project=&topics=&country=
**user:** 
Katharina M
**expected behaviour:** 
Sorting  in Idea Space Alphabetical shows ideas in alphabetical order
**behaviour:** 
It shows Internal Error Page
**important screensize:**
**device & browser:** 
MacBook Firefox 72.0.2 (64-Bit)
**Comment/Question:** 
They’re always telling me to live my dreams. But I don’t want to be naked in an exam I haven’t revised for.

Screenshot?

**Comment by fuzzylogic2000** [comment]
This should be fixed with the filter/idea-space-story, so is still to be done. I will close it here.
