### ISSUE TITLE
Enhancement: Larger Text field for Partner Details

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#354]
**URL:** https://ce-dev.liqd.net/ideas/meaningfull-title/
**user:** Admin
**expected behaviour:** If I enter the application form and come to "Partner Details"I am allowed to enter 400 characters. If I am enter the text I can see the whole text, or can widen the field so I can see the whole text
**behaviour:** There is just a small field and I cannot extend it to see the whole entered text.
**important screensize:**
**device & browser:**  Firefox 83.0
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2021-01-12 um 08 57 51](https://user-images.githubusercontent.com/52459078/104301835-646d2900-54c8-11eb-98b8-240ce254c138.png)

**Comment by phillimorland** [comment]
@hello-kathi do you want both the description and role fields to be larger or just the description?

**Comment by hello-kathi** [comment]
@phillimorland if possible both.
