### ISSUE TITLE
Application Form: Country Implamentation

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#355]
**URL:** https://ce-dev.liqd.net/ideas/meaningfull-title/
**user:** Admin
**expected behaviour:** I want to choose more then one country from a multiple choice choice, to choose the countries the project will be implemented
**behaviour:** I can scroll through a list and can choose just one. 
**important screensize:**
**device & browser:** Firefox 83.0
**Comment/Question:** It don't have to be a mandatory field if it makes things easier

Screenshot?
![Bildschirmfoto 2021-01-12 um 09 07 04](https://user-images.githubusercontent.com/52459078/104302408-09880180-54c9-11eb-8019-22281b6bccf2.png)

**Comment by Rineee** [comment]
@hello-kathi We already have an issue about that, see here issues/320. So currently you need to press shift to select multiple, which is of course not very intuitive.. possible solutions are in the other issue and we decided to wait for MitOst to tell us what they want? 
I'll close this and put the other in the milestone.
