### ISSUE TITLE
Idea Detail Page text Styling

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#357]
**URL:** https://ce-dev.liqd.net/ideas/meaningfull-title/
**user:** Admin
**expected behaviour:** The transferred text from the application form fits into the page layout
**behaviour:** The text get beyond the page layout
**important screensize:**
**device & browser:** Firefox 83.0 & Safari 14.1
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2021-01-12 um 11 17 39](https://user-images.githubusercontent.com/52459078/104303084-e9a50d80-54c9-11eb-8c7c-ed3203f91d96.png)

**Comment by phillimorland** [comment]
@hello-kathi as this is not an edge case (because words this long don't exist) and the 'fix' may cause issues for actual usage so i'll close this issue for now.
