### ISSUE TITLE
Budget in application form does not transfered correct on Idea detail page 

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#375]
**URL:** https://ce-stage.liqd.net/ideas/title/
**user:** Admin/Initiator
**expected behaviour:** If I type in the application form 50.000 for Budget, then it shows 50.000 or 50000 in the idea detail page
**behaviour:** The Idea detail page says: 50€
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
Kihihihi.

**Comment by phillimorland** [comment]
@phillimorland to test this. Preference is for no non whole numbers

**Comment by phillimorland** [comment]
@hello-kathi the number validation is built in and we are haveing trouble overiding it, @Rineee will give it one more go but if we can't what should the help text be to discourage decimal points?

**Comment by phillimorland** [comment]
@hello-kathi ok we definitely can't change the validation so we should add helptext, what do you think of:
"Please indicate your overall budget. The total budget may (but does not have to) include the applicant’s own contribution and/or external sources of funding. This section will be published in the idea space. Please only enter whole numbers, no decimal points or spaces."

**Comment by hello-kathi** [comment]
@phillimorland here you go: 
Please indicate your overall budget. The total budget may (but does not have to) include the applicant’s own contribution and/or external sources of funding. Please only enter whole numbers, no decimal signs like points, commas or spaces. This section will be published in the idea space.

**Comment by phillimorland** [comment]
@hello-kathi sorry should we also change it for requested funding, this is what it says now:

"Funding requested from Civic Europe can range from 1 to 50,000 EUR. Depending on your planning, the amount entered here can be the same as the “total budget” figure entered above. This section will be published in the idea space."
