### ISSUE TITLE
Facebook LogIn is not working

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#382]
**URL:**https://civic-europe.eu/
**user:** user
**expected behaviour:** I want to register with Facebook and Facebook support that
**behaviour:** It connects the user with Facebook but then an issue is coming up: "feature is not available"
**important screensize:**
**device & browser:** firefox, safari, chrome
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2021-02-04 um 11 00 24](https://user-images.githubusercontent.com/52459078/106883694-9dbc4180-66e0-11eb-9893-f8f035c79fd2.png)

**Comment by phillimorland** [comment]
@hello-kathi should be working again, please reopen if not
