### ISSUE TITLE
Structured Page don't display new Content

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#399]
**URL:** https://ce-stage.liqd.net/capacity-building-1/capacity-builiding/
**user:** admin
**expected behaviour:**As a Admin I tried to implement a new Block, here a FAQ and if I published it I can see that on the Live Website
**behaviour:** I create a new Block and safe and publish it but it is just seen partly

**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="1115" alt="Bildschirmfoto 2021-02-11 um 14 58 52" src="https://user-images.githubusercontent.com/52459078/107646479-4a1a9c80-6c7a-11eb-9165-be2bea8d9f33.png">

**Comment by phillimorland** [comment]
Note: when adding aligned images directly before FAQ block it splits space due to the float on the aligned image, maybe spacer div will ensure sections are separated? Also, remove the table headings of 'title' and  'content' and update styles see https://advocate-europe.eu/about/#section2

**Comment by fuzzylogic2000** [comment]
Haha, with doing the other issue, I understand your comment, @phillimorland . :) Now I will also have a go at the spacer div!
