### ISSUE TITLE
Styling 1-3 Column Text Block with two 1 Columns

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#411]
**URL:** https://ce-stage.liqd.net/capacity-building-1/200222-kathi-homepage/
**user:** Admin
**expected behaviour:** If I have a 1 Column Block and put two underneath each other there is a bit space between them
**behaviour:** There is no space between the 3 (as an example) 1-Column Blocks
**important screensize:**
**device & browser:** 

**Comment/Question:** 

Screenshot?
<img width="716" alt="Bildschirmfoto 2021-02-22 um 09 05 10" src="https://user-images.githubusercontent.com/52459078/108679664-31697c80-74ed-11eb-911b-55014c16258b.png">

**Comment by fuzzylogic2000** [comment]
The blocks are meant to use with the number of columns you chose. So, to do this, you need to add three one-column blocks with one column each. Does that make sense?

**Comment by phillimorland** [comment]
i'm leaving this open as it's an easy fix that i'll add if we do another release
