### ISSUE TITLE
Set random sample as default

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-civic-europe#436]
**URL:** https://ce-stage.liqd.net/ideas/
**user:** participant
**expected behaviour:** ideas in the idea space are shown randomly (on a daily basis) as a default
**behaviour:** current default sorting: Most comments

Unfortunately, this has to be implemented on prod until monday, 27th of April....

**Comment by hmkay** [comment]
Hello @fuzzylogic2000 @phillimorland @khamui ,

Unfortunately, this is quite an urgent matter. Civic Europe wrote me an E-Mail asking if we know that currently the daily random is not the default. The idea collection is ending on the 26th and from monday, the 27th on, the daily random sample should be the default of the sorting options in the idea space.

How do we make this possible?

**Comment by fuzzylogic2000** [comment]
The ordering should change together with the phases. It is defined here: https://github.com/liqd/a4-civic-europe/blob/master/apps/ideas/phases.py
It must have slipped us and them while implementing and testing the respective story. Can we find the story again to fix it for all phases?

**Comment by fuzzylogic2000** [comment]
Oh, but until Monday? Like before Monday? Deploy on prod on Friday?

**Comment by hmkay** [comment]
....I know :/ Yes, it must have slipped us. 

So if I get you right, it is bound to the phases? Meaning when the phase of the idea collection ends and the voting starts - then the random sampling is there?

Because that would be fine! We do not need the random sampling for all phases (would prob make sense, but that can wait), it is more important to have the random sampling there when the voting starts.

**Comment by fuzzylogic2000** [comment]
@hmkay We removed (or rather will remove) the sorting from all phases apart from the idea phase. It would be weird if the sorting would suddenly change while that phase is still on.
