### ISSUE TITLE
idea space and landing space keep showing the same projects

### ISSUE THREAD

**Issue by hmkay** [liqd/a4-civic-europe#441]
**URL:** https://civic-europe.eu/ideas/ AND https://civic-europe.eu/
**user:** participant
**expected behaviour:** ideas show randomly in idea space and on landing space meaning they change every day and for different people
**behaviour:** since about 18th/19th or 30th of April (exact date unclear), the same projects are shown always
**device & browser:** Firefox and Safari on Mac
**Comment/Question:** Is the landing page also showing random ideas? Or is it just the idea space?

**Comment by Rineee** [comment]
@hmkay Ok, so when we fixed the bug with the 'daily random' not being the default filter (we released on the 22nd), we did that for the next starting phase, which was starting on the 26th of April. So only from then on, the 'daily random' was the default on idea space. Before that it was still 'most commented', which probably doesnt change so much the order.
I tested it now locally and there everything is fine, the order changes for different dates. We would later also try to change the date on the server, to be super sure. And if that is also fine, I guess we would have to wait for tomorrow and see if the order changes? Would that be ok?

Concerning the landing page: that is a wagtail page and the ordering of the ideas can be chosen/set there.

**Comment by hmkay** [comment]
@Rineee cool, thanks for having such a quick look! 

What I understood from you is that you already found a solution locally and that you will put it on the server today. Do you mean the dev server with that?

Last time, I tested the daily random also via the privacy mode of firefox. Could we by that test it already today instead of waiting until tomorrow? 

And regarding the landing page: Thanks for the hint and yet again answering my questions... ;)

**Comment by Rineee** [comment]
@hmkay No, I tested the daily random for different dates and it is all fine (without changing anything). We would now check what happens on the (dev or stage) server if we change the date there.

**Comment by fuzzylogic2000** [comment]
@Rineee @hmkay Just to make very sure, that we talk about the right thing:
The filter changes only depending on the date, so there should be a different order every day, not with every reload. And as far as I know, also different users should on the same day see the same ordering. 
They do know that, right? And the order is not changing since the 26th of April in the idea space, even though, the filter says "daily random". Is that right? Did they take screenshots or note down the order? That would be helpful to have.

**Comment by hmkay** [comment]
@fuzzylogic2000 thanks for the sum up!

Yes, they know it is only every other day, not with every reload. I took a screenshot yesterday and today:

Yesterday:
<img width="792" alt="210503_idea space firefox" src="https://user-images.githubusercontent.com/30862422/116983794-d3b29700-acca-11eb-8c53-1f8574b48cd1.png">


Today:
<img width="830" alt="210504_idea space firefox" src="https://user-images.githubusercontent.com/30862422/116983890-eb8a1b00-acca-11eb-9bee-4b9da5decf8c.png">

I hope that helps!

**Comment by Rineee** [comment]
should be fixed by https://github.com/liqd/a4-civic-europe/pull/443 !443

**Comment by hmkay** [comment]
https://media.giphy.com/media/y8Mz1yj13s3kI/giphy.gif
