### ISSUE TITLE
date in comments initially show as invalid

### ISSUE THREAD

**Issue by Rineee** [liqd/a4-civic-europe#545]
**URL:** https://ce-dev.liqd.net/, not on stage
**user:** 
**expected behaviour:** The date is show correctly. 
**behaviour:** When I add a comment, it is shown as 'invalid date', when I reload the page, its fine
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
![image](https://user-images.githubusercontent.com/9589411/161085900-abc458f5-27cf-4b08-8f73-f1093b3ee526.png)

**Comment by khamui** [comment]
It seems that we use the "old" comments for ce, so the old comment.jsx converts the already in backend (translated and timzoned) created date again and gets an `Invalid date`. I am not totally sure why we receive the new created date on the api, but using the old jsx component?
