### ISSUE TITLE
dropdown on comments not working

### ISSUE THREAD

**Issue by Rineee** [liqd/a4-civic-europe#546]
**URL:** dev
**user:** 
**expected behaviour:** 
**behaviour:** dropdown to edit/remove comments doesnt work
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by khamui** [comment]
okay this seems to come from different versions of bootstrap (ce v4, a4 v5). because we are using the comments from a4, the bootstrap v5 dropdown does not work. upgrading ce to use bootstrap 5 might be a bigger task.

@Rineee @fuzzylogic2000 or do you have a better idea?

**Comment by fuzzylogic2000** [comment]
krah! But we do use the old comments, right? And everywhere else we are using the new comments by now. So, we could use bootstrap 4 js classes in the old comments? Not great, but äh, ehm, maybe easier than updating bootstrap!?
