### ISSUE TITLE
Video embed: smaller in pages created before update, youtube doesn't work

### ISSUE THREAD

**Issue by sabinammm** [liqd/a4-civic-europe#554]
**URL:** 
pre-update-created: https://ce-dev.liqd.net/ich-bin-eine-simple-page/ 
after-update-created: https://ce-dev.liqd.net/2022_03_test-structured-page/2022-04-blog-page/
**user:** admin
**expected behaviour:** All embed videos look the same
**behaviour:** Videos of same source that were added before all the updates, look smaller and are displayed without a title. Youtube links do not work at all. 
**important screensize:**
**device & browser:** chrome
**Comment/Question:** 
Only Vimeo and Youtube was tested
Screenshot?
**existing page displayed now (vimeo video same as in newly created page):**
![image](https://user-images.githubusercontent.com/17978375/161263686-cc89f1d5-750b-4595-9e4e-a6292d1c03ee.png)

**newly created page after updates with vimeo and youtube:**
![image](https://user-images.githubusercontent.com/17978375/161263837-dbe076cf-8503-495d-a023-993d5ad17726.png)

**Comment by khamui** [comment]
About the part `Youtube doesn't work` I could replicate with some Urls, but also for instance using this url it does work though: `https://youtu.be/J42SZXS-_Qo`

I am not sure what is the real problem, but I think it is not related to this `dev styling` task. So i am separating this issue into another issue. Hope thats fine.
