### ISSUE TITLE
Three-Image Block: images are not displayed correctly

### ISSUE THREAD

**Issue by sabinammm** [liqd/a4-civic-europe#555]
**URL:** https://ce-dev.liqd.net/200218-test/200218-test-homepage/
**user:** admin
**expected behaviour:** Images are displayed in right size 
**behaviour:** Images are very tiny
**important screensize:** 
**device & browser:** chrome
**Comment/Question:** 

Screenshot?
![image](https://user-images.githubusercontent.com/17978375/161265133-6b61af79-d61d-418a-bedf-441e96c50624.png)

**Comment by khamui** [comment]
If i am using the same images as on Prod, everything seems to be fine. So i am not sure if we should spent time on it right now @sabinammm ?

<img width="1369" alt="Bildschirmfoto 2022-04-04 um 17 10 07" src="https://user-images.githubusercontent.com/52801593/161586842-34b10fa8-8d83-46d2-874a-bd948f42b853.png">
