### ISSUE TITLE
1-3 Column Text Block not styled correctly

### ISSUE THREAD

**Issue by sabinammm** [liqd/a4-civic-europe#556]
**URL:** https://ce-dev.liqd.net/2022_03_test-structured-page/
**user:** Admin
**expected behaviour:** Text is distributed evenly in columns.
**behaviour:** Text is always only in 1 column, if 1 column is chosen, text is centred. There are older pages that disply this correclty (see screenshots)
**important screensize:**
**device & browser:** chrome
**Comment/Question:** 

Screenshot?
**newly created page:**
![image](https://user-images.githubusercontent.com/17978375/161266338-9062e7c3-72e7-4049-8f2f-4eb2ffe5a602.png)

**existing page where it still works:**
![image](https://user-images.githubusercontent.com/17978375/161266486-e07dcb37-bb73-4523-93d1-f6f491af03ea.png)

**Comment by phillimorland** [comment]
@sabinammm you need to add the columns within the block and add content for them to show up
