### ISSUE TITLE
Video embed: Youtube embeds are not showing

### ISSUE THREAD

**Issue by khamui** [liqd/a4-civic-europe#565]
**URL:** 
**user:** 
**expected behaviour:** Embedding youtube videos in wagtail pages shows a decent preview
**behaviour:** Does not show preview but `Video nicht verfügbar`
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot:
<img width="597" alt="Bildschirmfoto 2022-04-04 um 15 50 01" src="https://user-images.githubusercontent.com/52801593/161570450-8ff27367-5cc7-4263-b9fe-2f487c00c571.png">

**Comment by phillimorland** [comment]
depends on the permissions of teh video, in general seems to be fine https://ce-dev.liqd.net/ich-bin-eine-simple-page/
