### ISSUE TITLE
Wagtail - Video in FAQ Block Too small

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#570]
**URL:** https://ce-stage.liqd.net/dsfsdfdsfds/
**user:** Admin
**expected behaviour:** Same size like the other one in the FAQ Block
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="1368" alt="Bildschirmfoto 2022-04-20 um 09 27 32" src="https://user-images.githubusercontent.com/52459078/164174041-36f1269c-0874-4dbf-9325-e8df2dc87185.png">

**Comment by fuzzylogic2000** [comment]
@khamui Could you have a look?
