### ISSUE TITLE
the buttons on idea detail are displayd twice in medium screen size

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-civic-europe#71]
![Screenshot from 2020-03-06 11-38-11](https://user-images.githubusercontent.com/8178179/76076608-7a07ed00-5f9f-11ea-910b-8b1e6267a58c.png)
![Screenshot from 2020-03-06 11-37-09](https://user-images.githubusercontent.com/8178179/76076611-7aa08380-5f9f-11ea-892f-cf9689f94f1b.png)
![Screenshot from 2020-03-06 11-35-20](https://user-images.githubusercontent.com/8178179/76076612-7b391a00-5f9f-11ea-8ebf-ed3eab5032f2.png)
![Screenshot from 2020-03-06 11-34-49](https://user-images.githubusercontent.com/8178179/76076614-7bd1b080-5f9f-11ea-9b08-c761d6990e71.png)

**Comment by Rineee** [comment]
![grafik](https://user-images.githubusercontent.com/9589411/76300619-51446800-62bd-11ea-982c-eb40c5eb51f9.png)

![grafik](https://user-images.githubusercontent.com/9589411/76300765-91a3e600-62bd-11ea-92fd-f992ebc8888e.png)

![grafik](https://user-images.githubusercontent.com/9589411/76300830-aaac9700-62bd-11ea-91d7-c98c8d88be5e.png)


The tabs on idea detail page dont work for some screen sizes. Only when journey tab is there.
