### ISSUE TITLE
Error 403 After confirming registration

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-civic-europe#76]
**URL:** https://ce-dev.liqd.net/ideas/create/module/idea-challenge-2020/
**user:** initiator
**expected behaviour:** After clicking confirm registration on CE I want to come to Landingpage or LogIn
**behaviour:** *After I clicked confirm, I get an 403 Error. But WIth banner: You have confirmed and succesfully signed ina s Knopf_Inititaor
**important screensize:** desktop?
**device & browser:**Desktop, firefox 73.0.1 (64-Bit)
**Comment/Question:** 
<img width="1277" alt="Bildschirmfoto 2020-03-09 um 07 59 13" src="https://user-images.githubusercontent.com/52459078/76189977-406ff580-61dc-11ea-88da-1a03237192ba.png">

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.

**Comment by fuzzylogic2000** [comment]
This is a feature. :) You are not allowed to visit that page (and came there from the next)
